In [6]:
import numpy as np
print(np.__version__)


1.26.3


In [7]:
# Создание массивов из списков
a = np.array([1, 2, 3, 4, 5])
b = np.array([[1, 2, 3],
              [4, 5, 6]])

print("a:", a)
print("b:\n", b)

# zeros, ones, arange
zeros_arr = np.zeros((2, 3))
ones_arr = np.ones(4)
range_arr = np.arange(0, 10, 2)

print("zeros_arr:\n", zeros_arr)
print("ones_arr:", ones_arr)
print("range_arr:", range_arr)


a: [1 2 3 4 5]
b:
 [[1 2 3]
 [4 5 6]]
zeros_arr:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones_arr: [1. 1. 1. 1.]
range_arr: [0 2 4 6 8]


In [8]:
print("range_arr shape:", range_arr.shape)
print("range_arr dtype:", range_arr.dtype)

print("b shape:", b.shape)
print("b dtype:", b.dtype)


range_arr shape: (5,)
range_arr dtype: int32
b shape: (2, 3)
b dtype: int32


In [9]:
print("Первый элемент range_arr:", range_arr[0])
print("Последний элемент range_arr:", range_arr[-1])
print("Срез range_arr[1:4]:", range_arr[1:4])

print("Элемент b[0, 1]:", b[0, 1])
print("Вторая строка b[1, :]:", b[1, :])
print("Первый столбец b[:, 0]:", b[:, 0])


Первый элемент range_arr: 0
Последний элемент range_arr: 8
Срез range_arr[1:4]: [2 4 6]
Элемент b[0, 1]: 2
Вторая строка b[1, :]: [4 5 6]
Первый столбец b[:, 0]: [1 4]


In [10]:
x = np.array([1, 2, 3, 4])
y = np.array([10, 20, 30, 40])

print("x + y:", x + y)
print("x * y:", x * y)
print("mean(x):", x.mean())
print("max(y):", y.max())


x + y: [11 22 33 44]
x * y: [ 10  40  90 160]
mean(x): 2.5
max(y): 40
